import type { JobTemplateDefinition, SectorTemplateDefinition } from '../shared';

export const culture_creationTemplates: SectorTemplateDefinition = {
  sector: 'culture_creation',
  pack: {
    label: 'Arts / Culture / Création',
    signature: 'présenter une démarche créative et des œuvres avec des informations fidèles au projet',
    promoLead: 'annoncer une œuvre, une représentation, une exposition ou une rencontre confirmée',
    infoLead: 'partager les étapes de création, les influences et les actualités culturelles',
    followLead: 'suivre les demandes de collaboration, les commandes et les événements annoncés',
    surveyLead: 'comprendre les attentes du public et des partenaires pour un projet culturel',
    seasonal: 'actualité artistique ou culturelle de saison, si elle est confirmée',
    loyalty: 'nouveauté ou rencontre destinée aux personnes qui suivent déjà le travail créatif',
    maintenance: 'un rappel utile concernant une œuvre, une rencontre ou un projet en cours',
    localHook: 'création artistique et culturelle',
    audience: 'lecteurs, amateurs d’art, publics de spectacles et partenaires culturels',
  },
};

export const cultureCreationJobTemplates: JobTemplateDefinition[] = [
  {
    sector: 'culture_creation',
    professionKey: 'ecrivain_auteur',
    professionLabel: 'Écrivain / Auteur',
    pack: {
      label: 'Écrivain / Auteur',
      signature: 'faire découvrir un univers littéraire et les ouvrages réellement disponibles',
      promoLead: 'présenter un livre, une lecture ou une rencontre littéraire confirmée',
      infoLead: 'partager les coulisses de l’écriture, les thèmes des ouvrages et les actualités éditoriales',
      followLead: 'suivre une demande de rencontre, de dédicace ou de collaboration éditoriale',
      surveyLead: 'comprendre les envies de lecture ou les attentes pour un événement littéraire',
      seasonal: 'actualité d’un ouvrage ou événement littéraire de saison, si confirmé',
      loyalty: 'nouvelle lecture ou rencontre destinée aux lecteurs qui suivent déjà l’auteur',
      maintenance: 'un rappel utile pour une lecture, une rencontre ou un projet éditorial',
      localHook: 'livres et rencontres littéraires',
      audience: 'lecteurs, librairies, médiathèques et organisateurs de rencontres littéraires',
    },
  },
  {
    sector: 'culture_creation',
    professionKey: 'artiste',
    professionLabel: 'Artiste / Créateur',
    pack: {
      label: 'Artiste / Créateur',
      signature: 'présenter une démarche et des œuvres originales sans inventer de réalisation',
      promoLead: 'montrer une œuvre, une commande ou une exposition réellement proposée',
      infoLead: 'partager les recherches, matériaux et étapes d’un travail artistique',
      followLead: 'suivre les demandes d’œuvres, de collaborations et de rencontres',
      surveyLead: 'comprendre les goûts et les attentes autour d’un projet artistique',
      seasonal: 'exposition ou nouvelle création de saison, si confirmée',
      loyalty: 'nouvelle œuvre présentée aux personnes qui suivent déjà l’artiste',
      maintenance: 'un rappel utile pour une exposition ou un projet créatif',
      localHook: 'œuvres et créations artistiques',
      audience: 'amateurs d’art, lieux culturels, collectionneurs et partenaires créatifs',
    },
  },
  {
    sector: 'culture_creation',
    professionKey: 'artiste_peintre',
    professionLabel: 'Artiste peintre',
    pack: {
      label: 'Artiste peintre',
      signature: 'faire découvrir des tableaux, une technique picturale et un univers visuel',
      promoLead: 'présenter une toile, une série, une exposition ou une commande artistique confirmée',
      infoLead: 'partager les couleurs, les supports et les étapes de création d’un tableau',
      followLead: 'suivre les demandes de tableaux, de portraits et de visites d’exposition',
      surveyLead: 'comprendre les préférences visuelles pour une œuvre ou une commande',
      seasonal: 'nouvelle série de peintures ou exposition de saison, si confirmée',
      loyalty: 'nouvelle toile présentée aux personnes qui suivent déjà l’artiste',
      maintenance: 'un rappel utile pour voir une œuvre ou échanger sur une commande',
      localHook: 'peinture artistique et tableaux originaux',
      audience: 'amateurs de peinture, galeries, collectionneurs et commanditaires d’œuvres',
    },
  },
  {
    sector: 'culture_creation',
    professionKey: 'musicien_interprete',
    professionLabel: 'Musicien / Interprète',
    pack: {
      label: 'Musicien / Interprète',
      signature: 'présenter un univers musical, un répertoire et des prestations réellement proposées',
      promoLead: 'annoncer un concert, une session ou une prestation musicale confirmée',
      infoLead: 'partager le répertoire, les répétitions et les projets musicaux en cours',
      followLead: 'suivre les demandes de concert, d’enregistrement et de collaboration',
      surveyLead: 'comprendre l’ambiance et les besoins musicaux pour un événement',
      seasonal: 'concert ou projet musical de saison, si confirmé',
      loyalty: 'nouvelle interprétation destinée aux personnes qui suivent déjà le musicien',
      maintenance: 'un rappel utile pour un concert, une session ou une collaboration',
      localHook: 'musique interprétée en public ou en studio',
      audience: 'public de concerts, programmateurs et partenaires musicaux',
    },
  },
  {
    sector: 'culture_creation',
    professionKey: 'chanteur',
    professionLabel: 'Chanteur / Chanteuse',
    pack: {
      label: 'Chanteur / Chanteuse',
      signature: 'mettre en valeur une voix, un répertoire et des projets scéniques réels',
      promoLead: 'annoncer un concert, une prestation vocale ou un enregistrement confirmé',
      infoLead: 'partager le travail vocal, le répertoire et les coulisses d’un projet musical',
      followLead: 'suivre les demandes de prestation vocale, de concert et de collaboration',
      surveyLead: 'comprendre le répertoire ou l’ambiance recherchés pour une prestation',
      seasonal: 'représentation ou sortie musicale de saison, si confirmée',
      loyalty: 'nouvelle chanson ou rencontre destinée aux personnes qui suivent la voix',
      maintenance: 'un rappel utile pour une représentation ou une session vocale',
      localHook: 'chant et prestations vocales',
      audience: 'public de musique, salles, programmateurs et partenaires de scène',
    },
  },
  {
    sector: 'culture_creation',
    professionKey: 'compositeur',
    professionLabel: 'Compositeur / Compositrice',
    pack: {
      label: 'Compositeur / Compositrice',
      signature: 'présenter une écriture musicale originale et les projets sonores réalisés',
      promoLead: 'mettre en avant une composition, un arrangement ou une commande confirmée',
      infoLead: 'partager les choix d’écriture, les sonorités et les étapes de composition',
      followLead: 'suivre les briefs de composition, les retours et les collaborations',
      surveyLead: 'comprendre l’intention sonore et les contraintes d’un projet musical',
      seasonal: 'nouvelle composition ou sortie de saison, si confirmée',
      loyalty: 'nouvelle œuvre musicale destinée aux personnes qui suivent le compositeur',
      maintenance: 'un rappel utile pour un brief, une écoute ou une collaboration',
      localHook: 'compositions et créations musicales originales',
      audience: 'artistes, productions audiovisuelles, organisateurs et partenaires musicaux',
    },
  },
  {
    sector: 'culture_creation',
    professionKey: 'illustrateur',
    professionLabel: 'Illustrateur / Illustratrice',
    pack: {
      label: 'Illustrateur / Illustratrice',
      signature: 'montrer un style d’illustration et les images créées pour des projets réels',
      promoLead: 'présenter une illustration, une couverture ou une commande visuelle confirmée',
      infoLead: 'partager les croquis, les techniques et les étapes d’un projet illustré',
      followLead: 'suivre les demandes d’illustration, les retours et les collaborations',
      surveyLead: 'comprendre le style, le format et l’usage souhaités pour une illustration',
      seasonal: 'nouvelle série illustrée ou projet éditorial de saison, si confirmé',
      loyalty: 'nouvelle image destinée aux personnes qui suivent déjà l’illustrateur',
      maintenance: 'un rappel utile pour valider un brief ou découvrir une illustration',
      localHook: 'illustrations originales et projets éditoriaux',
      audience: 'éditeurs, auteurs, marques et amateurs d’illustration',
    },
  },
  {
    sector: 'culture_creation',
    professionKey: 'sculpteur',
    professionLabel: 'Sculpteur / Sculptrice',
    pack: {
      label: 'Sculpteur / Sculptrice',
      signature: 'présenter des volumes, des matières et des sculptures réellement créées',
      promoLead: 'montrer une sculpture, une exposition ou une commande confirmée',
      infoLead: 'partager le choix des matières et les étapes de création d’une pièce',
      followLead: 'suivre les demandes de sculpture, de visite et de collaboration',
      surveyLead: 'comprendre les dimensions, les matières et le lieu envisagés pour une œuvre',
      seasonal: 'nouvelle pièce ou exposition de saison, si confirmée',
      loyalty: 'nouvelle sculpture destinée aux personnes qui suivent déjà l’artiste',
      maintenance: 'un rappel utile pour découvrir une pièce ou avancer sur une commande',
      localHook: 'sculptures et œuvres en volume',
      audience: 'amateurs de sculpture, galeries, lieux culturels et commanditaires',
    },
  },
];
