export const DEFAULT_INRBADGE_LANGUAGE = "fr" as const;

export const INRBADGE_LANGUAGE_OPTIONS = [
  { value: "fr", label: "Français" },
  { value: "en", label: "English" },
  { value: "es", label: "Español" },
  { value: "it", label: "Italiano" },
  { value: "de", label: "Deutsch" },
  { value: "nl", label: "Nederlands" },
  { value: "pt", label: "Português" },
  { value: "th", label: "ไทย" },
  { value: "zh", label: "简体中文" },
] as const;

export type InrBadgeLanguageCode = (typeof INRBADGE_LANGUAGE_OPTIONS)[number]["value"];

const LANGUAGE_VALUES = new Set<string>(INRBADGE_LANGUAGE_OPTIONS.map((option) => option.value));

export function normalizeInrBadgeLanguage(value: unknown): InrBadgeLanguageCode {
  const raw = String(value || "").trim().toLowerCase();
  if (LANGUAGE_VALUES.has(raw)) return raw as InrBadgeLanguageCode;
  const base = raw.split(/[-_]/)[0];
  return LANGUAGE_VALUES.has(base) ? (base as InrBadgeLanguageCode) : DEFAULT_INRBADGE_LANGUAGE;
}

export function getInrBadgeLocale(language: unknown) {
  const lang = normalizeInrBadgeLanguage(language);
  if (lang === "en") return "en-GB";
  if (lang === "es") return "es-ES";
  if (lang === "it") return "it-IT";
  if (lang === "de") return "de-DE";
  if (lang === "nl") return "nl-NL";
  if (lang === "pt") return "pt-PT";
  if (lang === "th") return "th-TH";
  if (lang === "zh") return "zh-CN";
  return "fr-FR";
}

export type InrBadgeTexts = {
  close: string;
  shareAria: string;
  shareTitle: string;
  shareSheetTitle: string;
  shareSheetDescription: string;
  shareNative: string;
  shareNativeHelper: string;
  copyLink: string;
  copyLinkHelper: string;
  install: string;
  installHelper: string;
  linkCopied: string;
  linkCopiedClipboard: string;
  copyUnavailable: string;
  alreadyInstalled: string;
  installRequested: string;
  installFailed: string;
  iosInstallHelp: string;
  androidInstallHelp: string;
  shareTextPrefix: string;
  call: string;
  mail: string;
  saveContact: string;
  sendDetails: string;
  findUs: string;
  appointment: string;
  openingHours: string;
  interventionZones: string;
  poweredBy: string;
  leadIdentityError: string;
  leadConsentError: string;
  leadGenericError: string;
  leadDialogTitle: string;
  leadSentTitle: string;
  leadSentText: string;
  leadNameLabel: string;
  leadNamePlaceholder: string;
  phoneLabel: string;
  emailLabel: string;
  leadMessageLabel: string;
  leadMessagePlaceholder: string;
  leadConsent: string;
  leadSubmitting: string;
  leadSubmit: string;
  rdvMetaTitle: string;
  rdvTitle: string;
  rdvChooseSlot: string;
  rdvDate: string;
  rdvTime: string;
  rdvChooseTime: string;
  rdvNoSlot: string;
  rdvNoSlotDay: string;
  rdvNameLabel: string;
  rdvNamePlaceholder: string;
  rdvCompanyLabel: string;
  rdvCompanyPlaceholder: string;
  rdvMailLabel: string;
  rdvEmailPlaceholder: string;
  rdvPhoneLabel: string;
  rdvPhonePlaceholder: string;
  rdvMessageLabel: string;
  rdvMessagePlaceholder: string;
  rdvChooseSlotError: string;
  rdvRequiredError: string;
  rdvGenericError: string;
  rdvSuccess: string;
  rdvSubmitting: string;
  rdvSubmit: string;
  rdvNote: string;
  rdvBack: string;
};

const TEXTS: Record<InrBadgeLanguageCode, InrBadgeTexts> = {
  fr: {
    close: "Fermer",
    shareAria: "Partager cette fiche",
    shareTitle: "Partager",
    shareSheetTitle: "Fiche contact",
    shareSheetDescription: "Partagez cette fiche, copiez son lien ou ajoutez-la à votre écran d’accueil.",
    shareNative: "Partager",
    shareNativeHelper: "WhatsApp, SMS, mail…",
    copyLink: "Copier le lien",
    copyLinkHelper: "Conserver la fiche pour plus tard",
    install: "Ajouter à l'écran d'accueil",
    installHelper: "iPhone / Android",
    linkCopied: "Lien copié. Vous pouvez maintenant le partager où vous voulez.",
    linkCopiedClipboard: "Lien copié dans le presse-papiers.",
    copyUnavailable: "Impossible de copier automatiquement. Vous pouvez sélectionner l'URL et la copier manuellement.",
    alreadyInstalled: "Cette fiche est déjà disponible sur l'écran d'accueil de ce téléphone.",
    installRequested: "Demande d'ajout à l'écran d'accueil envoyée.",
    installFailed: "L'ajout à l'écran d'accueil n'a pas pu être lancé.",
    iosInstallHelp: "Sur iPhone : appuyez sur Partager dans Safari, puis choisissez “Sur l’écran d’accueil”.",
    androidInstallHelp: "Sur Android : ouvrez le menu du navigateur puis choisissez “Ajouter à l’écran d’accueil” ou “Installer l’application”.",
    shareTextPrefix: "Découvrez",
    call: "Appeler",
    mail: "Mail",
    saveContact: "Enregistrer",
    sendDetails: "Transmettre mes coordonnées",
    findUs: "Retrouvez-nous",
    appointment: "Prendre RDV",
    openingHours: "Horaires",
    interventionZones: "Zones d’intervention",
    poweredBy: "Propulsé par",
    leadIdentityError: "Renseignez au moins un nom, un mail ou un téléphone.",
    leadConsentError: "La validation est nécessaire pour transmettre vos coordonnées.",
    leadGenericError: "Impossible de transmettre vos coordonnées.",
    leadDialogTitle: "Transmettre mes coordonnées",
    leadSentTitle: "C’est envoyé.",
    leadSentText: "Le professionnel a bien reçu vos coordonnées.",
    leadNameLabel: "Nom Prénom / Raison sociale",
    leadNamePlaceholder: "Dupont Marie / SAS Exemple",
    phoneLabel: "Téléphone",
    emailLabel: "Email",
    leadMessageLabel: "Message / demande",
    leadMessagePlaceholder: "Votre demande, besoin ou créneau préféré…",
    leadConsent: "J’accepte que mes coordonnées soient transmises à ce professionnel.",
    leadSubmitting: "Transmission…",
    leadSubmit: "Envoyer mes coordonnées",
    rdvMetaTitle: "Prendre RDV - iNr'Badge",
    rdvTitle: "Réserver un rendez-vous",
    rdvChooseSlot: "Choisir un créneau",
    rdvDate: "Date",
    rdvTime: "Horaire",
    rdvChooseTime: "Choisir un horaire",
    rdvNoSlot: "Aucun créneau",
    rdvNoSlotDay: "Aucun créneau disponible sur cette journée.",
    rdvNameLabel: "Nom / prénom *",
    rdvNamePlaceholder: "Votre nom",
    rdvCompanyLabel: "Société",
    rdvCompanyPlaceholder: "Votre société",
    rdvMailLabel: "Mail *",
    rdvEmailPlaceholder: "votre@email.fr",
    rdvPhoneLabel: "Téléphone",
    rdvPhonePlaceholder: "06...",
    rdvMessageLabel: "Message / motif",
    rdvMessagePlaceholder: "Expliquez rapidement votre besoin",
    rdvChooseSlotError: "Choisissez un créneau.",
    rdvRequiredError: "Nom et email sont obligatoires.",
    rdvGenericError: "Impossible d'envoyer la demande.",
    rdvSuccess: "Demande envoyée. Le professionnel va confirmer ou proposer un autre créneau.",
    rdvSubmitting: "Envoi...",
    rdvSubmit: "Envoyer la demande",
    rdvNote: "Le rendez-vous sera enregistré dans iNr'Calendar uniquement après validation du professionnel.",
    rdvBack: "Retour à la fiche",
  },
  en: {
    close: "Close",
    shareAria: "Share this card",
    shareTitle: "Share",
    shareSheetTitle: "Contact card",
    shareSheetDescription: "Share this card, copy its link or add it to your home screen.",
    shareNative: "Share",
    shareNativeHelper: "WhatsApp, SMS, email…",
    copyLink: "Copy link",
    copyLinkHelper: "Save the card for later",
    install: "Add to home screen",
    installHelper: "iPhone / Android",
    linkCopied: "Link copied. You can now share it anywhere.",
    linkCopiedClipboard: "Link copied to clipboard.",
    copyUnavailable: "Unable to copy automatically. You can select the URL and copy it manually.",
    alreadyInstalled: "This card is already available on this phone's home screen.",
    installRequested: "Home screen add request sent.",
    installFailed: "The home screen add action could not be started.",
    iosInstallHelp: "On iPhone: tap Share in Safari, then choose “Add to Home Screen”.",
    androidInstallHelp: "On Android: open the browser menu, then choose “Add to Home screen” or “Install app”.",
    shareTextPrefix: "Discover",
    call: "Call",
    mail: "Email",
    saveContact: "Save",
    sendDetails: "Send my details",
    findUs: "Find us",
    appointment: "Book appointment",
    openingHours: "Opening hours",
    interventionZones: "Service areas",
    poweredBy: "Powered by",
    leadIdentityError: "Enter at least a name, an email or a phone number.",
    leadConsentError: "Consent is required to send your details.",
    leadGenericError: "Unable to send your details.",
    leadDialogTitle: "Send my details",
    leadSentTitle: "Sent.",
    leadSentText: "The professional has received your details.",
    leadNameLabel: "Full name / Company",
    leadNamePlaceholder: "Mary Smith / Example Ltd",
    phoneLabel: "Phone",
    emailLabel: "Email",
    leadMessageLabel: "Message / request",
    leadMessagePlaceholder: "Your request, need or preferred time…",
    leadConsent: "I agree that my details are sent to this professional.",
    leadSubmitting: "Sending…",
    leadSubmit: "Send my details",
    rdvMetaTitle: "Book appointment - iNr'Badge",
    rdvTitle: "Book an appointment",
    rdvChooseSlot: "Choose a time slot",
    rdvDate: "Date",
    rdvTime: "Time",
    rdvChooseTime: "Choose a time",
    rdvNoSlot: "No slot",
    rdvNoSlotDay: "No time slot available on this day.",
    rdvNameLabel: "Full name *",
    rdvNamePlaceholder: "Your name",
    rdvCompanyLabel: "Company",
    rdvCompanyPlaceholder: "Your company",
    rdvMailLabel: "Email *",
    rdvEmailPlaceholder: "your@email.com",
    rdvPhoneLabel: "Phone",
    rdvPhonePlaceholder: "Phone number",
    rdvMessageLabel: "Message / reason",
    rdvMessagePlaceholder: "Briefly explain your need",
    rdvChooseSlotError: "Choose a time slot.",
    rdvRequiredError: "Name and email are required.",
    rdvGenericError: "Unable to send the request.",
    rdvSuccess: "Request sent. The professional will confirm or suggest another time slot.",
    rdvSubmitting: "Sending...",
    rdvSubmit: "Send request",
    rdvNote: "The appointment will be added to iNr'Calendar only after the professional confirms it.",
    rdvBack: "Back to card",
  },
  es: {
    close: "Cerrar",
    shareAria: "Compartir esta ficha",
    shareTitle: "Compartir",
    shareSheetTitle: "Ficha de contacto",
    shareSheetDescription: "Comparte esta ficha, copia su enlace o añádela a la pantalla de inicio.",
    shareNative: "Compartir",
    shareNativeHelper: "WhatsApp, SMS, email…",
    copyLink: "Copiar enlace",
    copyLinkHelper: "Guardar la ficha para más tarde",
    install: "Añadir a la pantalla de inicio",
    installHelper: "iPhone / Android",
    linkCopied: "Enlace copiado. Ya puedes compartirlo donde quieras.",
    linkCopiedClipboard: "Enlace copiado al portapapeles.",
    copyUnavailable: "No se puede copiar automáticamente. Puedes seleccionar la URL y copiarla manualmente.",
    alreadyInstalled: "Esta ficha ya está disponible en la pantalla de inicio de este teléfono.",
    installRequested: "Solicitud para añadir a la pantalla de inicio enviada.",
    installFailed: "No se pudo iniciar la acción de añadir a la pantalla de inicio.",
    iosInstallHelp: "En iPhone: toca Compartir en Safari y elige “Añadir a pantalla de inicio”.",
    androidInstallHelp: "En Android: abre el menú del navegador y elige “Añadir a pantalla de inicio” o “Instalar aplicación”.",
    shareTextPrefix: "Descubre",
    call: "Llamar",
    mail: "Email",
    saveContact: "Guardar",
    sendDetails: "Enviar mis datos",
    findUs: "Encuéntranos",
    appointment: "Reservar cita",
    openingHours: "Horarios",
    interventionZones: "Zonas de intervención",
    poweredBy: "Desarrollado por",
    leadIdentityError: "Introduce al menos un nombre, email o teléfono.",
    leadConsentError: "El consentimiento es necesario para enviar tus datos.",
    leadGenericError: "No se pueden enviar tus datos.",
    leadDialogTitle: "Enviar mis datos",
    leadSentTitle: "Enviado.",
    leadSentText: "El profesional ha recibido tus datos.",
    leadNameLabel: "Nombre / Empresa",
    leadNamePlaceholder: "María López / SAS Ejemplo",
    phoneLabel: "Teléfono",
    emailLabel: "Email",
    leadMessageLabel: "Mensaje / solicitud",
    leadMessagePlaceholder: "Tu solicitud, necesidad u horario preferido…",
    leadConsent: "Acepto que mis datos sean enviados a este profesional.",
    leadSubmitting: "Enviando…",
    leadSubmit: "Enviar mis datos",
    rdvMetaTitle: "Reservar cita - iNr'Badge",
    rdvTitle: "Reservar una cita",
    rdvChooseSlot: "Elegir un horario",
    rdvDate: "Fecha",
    rdvTime: "Hora",
    rdvChooseTime: "Elegir una hora",
    rdvNoSlot: "Sin horario",
    rdvNoSlotDay: "No hay horarios disponibles para este día.",
    rdvNameLabel: "Nombre *",
    rdvNamePlaceholder: "Tu nombre",
    rdvCompanyLabel: "Empresa",
    rdvCompanyPlaceholder: "Tu empresa",
    rdvMailLabel: "Email *",
    rdvEmailPlaceholder: "tu@email.com",
    rdvPhoneLabel: "Teléfono",
    rdvPhonePlaceholder: "Teléfono",
    rdvMessageLabel: "Mensaje / motivo",
    rdvMessagePlaceholder: "Explica brevemente tu necesidad",
    rdvChooseSlotError: "Elige un horario.",
    rdvRequiredError: "El nombre y el email son obligatorios.",
    rdvGenericError: "No se puede enviar la solicitud.",
    rdvSuccess: "Solicitud enviada. El profesional confirmará o propondrá otro horario.",
    rdvSubmitting: "Enviando...",
    rdvSubmit: "Enviar solicitud",
    rdvNote: "La cita se añadirá a iNr'Calendar solo después de la validación del profesional.",
    rdvBack: "Volver a la ficha",
  },
  it: {
    close: "Chiudere",
    shareAria: "Condividi questa scheda",
    shareTitle: "Condividi",
    shareSheetTitle: "Scheda contatto",
    shareSheetDescription: "Condividi questa scheda, copia il link o aggiungila alla schermata Home.",
    shareNative: "Condividi",
    shareNativeHelper: "WhatsApp, SMS, email…",
    copyLink: "Copia link",
    copyLinkHelper: "Salva la scheda per dopo",
    install: "Aggiungi alla schermata Home",
    installHelper: "iPhone / Android",
    linkCopied: "Link copiato. Ora puoi condividerlo dove vuoi.",
    linkCopiedClipboard: "Link copiato negli appunti.",
    copyUnavailable: "Impossibile copiare automaticamente. Puoi selezionare l'URL e copiarlo manualmente.",
    alreadyInstalled: "Questa scheda è già disponibile sulla schermata Home di questo telefono.",
    installRequested: "Richiesta di aggiunta alla schermata Home inviata.",
    installFailed: "Impossibile avviare l'aggiunta alla schermata Home.",
    iosInstallHelp: "Su iPhone: tocca Condividi in Safari, poi scegli “Aggiungi alla schermata Home”.",
    androidInstallHelp: "Su Android: apri il menu del browser e scegli “Aggiungi alla schermata Home” o “Installa app”.",
    shareTextPrefix: "Scopri",
    call: "Chiamare",
    mail: "Email",
    saveContact: "Salvare",
    sendDetails: "Inviare i miei dati",
    findUs: "Trovaci",
    appointment: "Prenota appuntamento",
    openingHours: "Orari",
    interventionZones: "Zone di intervento",
    poweredBy: "Powered by",
    leadIdentityError: "Inserisci almeno un nome, un'email o un telefono.",
    leadConsentError: "Il consenso è necessario per inviare i tuoi dati.",
    leadGenericError: "Impossibile inviare i tuoi dati.",
    leadDialogTitle: "Inviare i miei dati",
    leadSentTitle: "Inviato.",
    leadSentText: "Il professionista ha ricevuto i tuoi dati.",
    leadNameLabel: "Nome / Azienda",
    leadNamePlaceholder: "Maria Rossi / Esempio SRL",
    phoneLabel: "Telefono",
    emailLabel: "Email",
    leadMessageLabel: "Messaggio / richiesta",
    leadMessagePlaceholder: "La tua richiesta, esigenza o orario preferito…",
    leadConsent: "Accetto che i miei dati siano inviati a questo professionista.",
    leadSubmitting: "Invio…",
    leadSubmit: "Inviare i miei dati",
    rdvMetaTitle: "Prenota appuntamento - iNr'Badge",
    rdvTitle: "Prenota un appuntamento",
    rdvChooseSlot: "Scegli una fascia oraria",
    rdvDate: "Data",
    rdvTime: "Orario",
    rdvChooseTime: "Scegli un orario",
    rdvNoSlot: "Nessuna fascia",
    rdvNoSlotDay: "Nessuna fascia oraria disponibile per questo giorno.",
    rdvNameLabel: "Nome *",
    rdvNamePlaceholder: "Il tuo nome",
    rdvCompanyLabel: "Azienda",
    rdvCompanyPlaceholder: "La tua azienda",
    rdvMailLabel: "Email *",
    rdvEmailPlaceholder: "tua@email.com",
    rdvPhoneLabel: "Telefono",
    rdvPhonePlaceholder: "Telefono",
    rdvMessageLabel: "Messaggio / motivo",
    rdvMessagePlaceholder: "Spiega brevemente la tua esigenza",
    rdvChooseSlotError: "Scegli una fascia oraria.",
    rdvRequiredError: "Nome ed email sono obbligatori.",
    rdvGenericError: "Impossibile inviare la richiesta.",
    rdvSuccess: "Richiesta inviata. Il professionista confermerà o proporrà un altro orario.",
    rdvSubmitting: "Invio...",
    rdvSubmit: "Invia richiesta",
    rdvNote: "L'appuntamento verrà aggiunto a iNr'Calendar solo dopo la conferma del professionista.",
    rdvBack: "Torna alla scheda",
  },
  de: {
    close: "Schließen",
    shareAria: "Diese Karte teilen",
    shareTitle: "Teilen",
    shareSheetTitle: "Kontaktkarte",
    shareSheetDescription: "Teilen Sie diese Karte, kopieren Sie den Link oder fügen Sie sie zum Startbildschirm hinzu.",
    shareNative: "Teilen",
    shareNativeHelper: "WhatsApp, SMS, E-Mail…",
    copyLink: "Link kopieren",
    copyLinkHelper: "Karte für später speichern",
    install: "Zum Startbildschirm hinzufügen",
    installHelper: "iPhone / Android",
    linkCopied: "Link kopiert. Sie können ihn jetzt überall teilen.",
    linkCopiedClipboard: "Link in die Zwischenablage kopiert.",
    copyUnavailable: "Automatisches Kopieren nicht möglich. Sie können die URL manuell auswählen und kopieren.",
    alreadyInstalled: "Diese Karte ist bereits auf dem Startbildschirm dieses Telefons verfügbar.",
    installRequested: "Anfrage zum Hinzufügen zum Startbildschirm gesendet.",
    installFailed: "Das Hinzufügen zum Startbildschirm konnte nicht gestartet werden.",
    iosInstallHelp: "Auf dem iPhone: Tippen Sie in Safari auf Teilen und wählen Sie „Zum Home-Bildschirm“.",
    androidInstallHelp: "Auf Android: Öffnen Sie das Browser-Menü und wählen Sie „Zum Startbildschirm hinzufügen“ oder „App installieren“.",
    shareTextPrefix: "Entdecken Sie",
    call: "Anrufen",
    mail: "E-Mail",
    saveContact: "Speichern",
    sendDetails: "Meine Kontaktdaten senden",
    findUs: "Finden Sie uns",
    appointment: "Termin buchen",
    openingHours: "Öffnungszeiten",
    interventionZones: "Einsatzgebiete",
    poweredBy: "Bereitgestellt von",
    leadIdentityError: "Geben Sie mindestens einen Namen, eine E-Mail oder eine Telefonnummer ein.",
    leadConsentError: "Ihre Zustimmung ist erforderlich, um Ihre Daten zu senden.",
    leadGenericError: "Ihre Kontaktdaten konnten nicht gesendet werden.",
    leadDialogTitle: "Meine Kontaktdaten senden",
    leadSentTitle: "Gesendet.",
    leadSentText: "Der Anbieter hat Ihre Kontaktdaten erhalten.",
    leadNameLabel: "Name / Unternehmen",
    leadNamePlaceholder: "Maria Müller / Beispiel GmbH",
    phoneLabel: "Telefon",
    emailLabel: "E-Mail",
    leadMessageLabel: "Nachricht / Anfrage",
    leadMessagePlaceholder: "Ihre Anfrage, Ihr Bedarf oder Wunschzeitraum…",
    leadConsent: "Ich stimme zu, dass meine Kontaktdaten an diesen Anbieter gesendet werden.",
    leadSubmitting: "Senden…",
    leadSubmit: "Meine Daten senden",
    rdvMetaTitle: "Termin buchen - iNr'Badge",
    rdvTitle: "Termin buchen",
    rdvChooseSlot: "Zeitfenster wählen",
    rdvDate: "Datum",
    rdvTime: "Uhrzeit",
    rdvChooseTime: "Uhrzeit wählen",
    rdvNoSlot: "Kein Zeitfenster",
    rdvNoSlotDay: "Für diesen Tag ist kein Zeitfenster verfügbar.",
    rdvNameLabel: "Name *",
    rdvNamePlaceholder: "Ihr Name",
    rdvCompanyLabel: "Unternehmen",
    rdvCompanyPlaceholder: "Ihr Unternehmen",
    rdvMailLabel: "E-Mail *",
    rdvEmailPlaceholder: "ihre@email.de",
    rdvPhoneLabel: "Telefon",
    rdvPhonePlaceholder: "Telefonnummer",
    rdvMessageLabel: "Nachricht / Grund",
    rdvMessagePlaceholder: "Beschreiben Sie kurz Ihr Anliegen",
    rdvChooseSlotError: "Wählen Sie ein Zeitfenster.",
    rdvRequiredError: "Name und E-Mail sind erforderlich.",
    rdvGenericError: "Die Anfrage konnte nicht gesendet werden.",
    rdvSuccess: "Anfrage gesendet. Der Anbieter bestätigt den Termin oder schlägt eine andere Zeit vor.",
    rdvSubmitting: "Senden...",
    rdvSubmit: "Anfrage senden",
    rdvNote: "Der Termin wird erst nach Bestätigung durch den Anbieter in iNr'Calendar eingetragen.",
    rdvBack: "Zurück zur Karte",
  },
  nl: {
    close: "Sluiten",
    shareAria: "Deze kaart delen",
    shareTitle: "Delen",
    shareSheetTitle: "Contactkaart",
    shareSheetDescription: "Deel deze kaart, kopieer de link of voeg hem toe aan je startscherm.",
    shareNative: "Delen",
    shareNativeHelper: "WhatsApp, sms, e-mail…",
    copyLink: "Link kopiëren",
    copyLinkHelper: "Bewaar de kaart voor later",
    install: "Toevoegen aan startscherm",
    installHelper: "iPhone / Android",
    linkCopied: "Link gekopieerd. Je kunt hem nu overal delen.",
    linkCopiedClipboard: "Link gekopieerd naar het klembord.",
    copyUnavailable: "Automatisch kopiëren is niet mogelijk. Je kunt de URL selecteren en handmatig kopiëren.",
    alreadyInstalled: "Deze kaart staat al op het startscherm van deze telefoon.",
    installRequested: "Verzoek om toe te voegen aan startscherm verzonden.",
    installFailed: "Toevoegen aan startscherm kon niet worden gestart.",
    iosInstallHelp: "Op iPhone: tik op Delen in Safari en kies “Zet op beginscherm”.",
    androidInstallHelp: "Op Android: open het browsermenu en kies “Toevoegen aan startscherm” of “App installeren”.",
    shareTextPrefix: "Ontdek",
    call: "Bellen",
    mail: "E-mail",
    saveContact: "Opslaan",
    sendDetails: "Mijn gegevens verzenden",
    findUs: "Vind ons",
    appointment: "Afspraak maken",
    openingHours: "Openingstijden",
    interventionZones: "Werkgebieden",
    poweredBy: "Aangedreven door",
    leadIdentityError: "Vul minstens een naam, e-mail of telefoonnummer in.",
    leadConsentError: "Toestemming is nodig om je gegevens te verzenden.",
    leadGenericError: "Je gegevens kunnen niet worden verzonden.",
    leadDialogTitle: "Mijn gegevens verzenden",
    leadSentTitle: "Verzonden.",
    leadSentText: "De professional heeft je gegevens ontvangen.",
    leadNameLabel: "Naam / Bedrijf",
    leadNamePlaceholder: "Maria Jansen / Voorbeeld BV",
    phoneLabel: "Telefoon",
    emailLabel: "E-mail",
    leadMessageLabel: "Bericht / aanvraag",
    leadMessagePlaceholder: "Je aanvraag, behoefte of gewenste tijd…",
    leadConsent: "Ik ga ermee akkoord dat mijn gegevens naar deze professional worden verzonden.",
    leadSubmitting: "Verzenden…",
    leadSubmit: "Mijn gegevens verzenden",
    rdvMetaTitle: "Afspraak maken - iNr'Badge",
    rdvTitle: "Een afspraak maken",
    rdvChooseSlot: "Kies een tijdslot",
    rdvDate: "Datum",
    rdvTime: "Tijd",
    rdvChooseTime: "Kies een tijd",
    rdvNoSlot: "Geen tijdslot",
    rdvNoSlotDay: "Geen tijdslot beschikbaar op deze dag.",
    rdvNameLabel: "Naam *",
    rdvNamePlaceholder: "Je naam",
    rdvCompanyLabel: "Bedrijf",
    rdvCompanyPlaceholder: "Je bedrijf",
    rdvMailLabel: "E-mail *",
    rdvEmailPlaceholder: "jij@email.nl",
    rdvPhoneLabel: "Telefoon",
    rdvPhonePlaceholder: "Telefoonnummer",
    rdvMessageLabel: "Bericht / reden",
    rdvMessagePlaceholder: "Leg kort uit wat je nodig hebt",
    rdvChooseSlotError: "Kies een tijdslot.",
    rdvRequiredError: "Naam en e-mail zijn verplicht.",
    rdvGenericError: "De aanvraag kan niet worden verzonden.",
    rdvSuccess: "Aanvraag verzonden. De professional bevestigt of stelt een ander tijdslot voor.",
    rdvSubmitting: "Verzenden...",
    rdvSubmit: "Aanvraag verzenden",
    rdvNote: "De afspraak wordt pas na bevestiging door de professional toegevoegd aan iNr'Calendar.",
    rdvBack: "Terug naar kaart",
  },
  pt: {
    close: "Fechar",
    shareAria: "Partilhar esta ficha",
    shareTitle: "Partilhar",
    shareSheetTitle: "Ficha de contacto",
    shareSheetDescription: "Partilhe esta ficha, copie o link ou adicione-a ao ecrã inicial.",
    shareNative: "Partilhar",
    shareNativeHelper: "WhatsApp, SMS, email…",
    copyLink: "Copiar link",
    copyLinkHelper: "Guardar a ficha para mais tarde",
    install: "Adicionar ao ecrã inicial",
    installHelper: "iPhone / Android",
    linkCopied: "Link copiado. Já pode partilhá-lo onde quiser.",
    linkCopiedClipboard: "Link copiado para a área de transferência.",
    copyUnavailable: "Não foi possível copiar automaticamente. Pode selecionar o URL e copiá-lo manualmente.",
    alreadyInstalled: "Esta ficha já está disponível no ecrã inicial deste telemóvel.",
    installRequested: "Pedido para adicionar ao ecrã inicial enviado.",
    installFailed: "Não foi possível iniciar a adição ao ecrã inicial.",
    iosInstallHelp: "No iPhone: toque em Partilhar no Safari e escolha “Adicionar ao ecrã principal”.",
    androidInstallHelp: "No Android: abra o menu do navegador e escolha “Adicionar ao ecrã inicial” ou “Instalar aplicação”.",
    shareTextPrefix: "Descubra",
    call: "Ligar",
    mail: "Email",
    saveContact: "Guardar",
    sendDetails: "Enviar os meus dados",
    findUs: "Encontre-nos",
    appointment: "Marcar consulta",
    openingHours: "Horários",
    interventionZones: "Zonas de intervenção",
    poweredBy: "Criado por",
    leadIdentityError: "Indique pelo menos um nome, email ou telefone.",
    leadConsentError: "O consentimento é necessário para enviar os seus dados.",
    leadGenericError: "Não foi possível enviar os seus dados.",
    leadDialogTitle: "Enviar os meus dados",
    leadSentTitle: "Enviado.",
    leadSentText: "O profissional recebeu os seus dados.",
    leadNameLabel: "Nome / Empresa",
    leadNamePlaceholder: "Maria Silva / Empresa Exemplo",
    phoneLabel: "Telefone",
    emailLabel: "Email",
    leadMessageLabel: "Mensagem / pedido",
    leadMessagePlaceholder: "O seu pedido, necessidade ou horário preferido…",
    leadConsent: "Aceito que os meus dados sejam enviados a este profissional.",
    leadSubmitting: "A enviar…",
    leadSubmit: "Enviar os meus dados",
    rdvMetaTitle: "Marcar consulta - iNr'Badge",
    rdvTitle: "Marcar uma consulta",
    rdvChooseSlot: "Escolher um horário",
    rdvDate: "Data",
    rdvTime: "Horário",
    rdvChooseTime: "Escolher um horário",
    rdvNoSlot: "Sem horário",
    rdvNoSlotDay: "Não há horários disponíveis neste dia.",
    rdvNameLabel: "Nome *",
    rdvNamePlaceholder: "O seu nome",
    rdvCompanyLabel: "Empresa",
    rdvCompanyPlaceholder: "A sua empresa",
    rdvMailLabel: "Email *",
    rdvEmailPlaceholder: "seu@email.pt",
    rdvPhoneLabel: "Telefone",
    rdvPhonePlaceholder: "Telefone",
    rdvMessageLabel: "Mensagem / motivo",
    rdvMessagePlaceholder: "Explique brevemente a sua necessidade",
    rdvChooseSlotError: "Escolha um horário.",
    rdvRequiredError: "Nome e email são obrigatórios.",
    rdvGenericError: "Não foi possível enviar o pedido.",
    rdvSuccess: "Pedido enviado. O profissional irá confirmar ou propor outro horário.",
    rdvSubmitting: "A enviar...",
    rdvSubmit: "Enviar pedido",
    rdvNote: "A consulta só será adicionada ao iNr'Calendar após validação do profissional.",
    rdvBack: "Voltar à ficha",
  },
  th: {
    close: "ปิด",
    shareAria: "แชร์นามบัตรนี้",
    shareTitle: "แชร์",
    shareSheetTitle: "นามบัตรติดต่อ",
    shareSheetDescription: "แชร์นามบัตรนี้ คัดลอกลิงก์ หรือเพิ่มไปยังหน้าจอหลัก",
    shareNative: "แชร์",
    shareNativeHelper: "WhatsApp, SMS, อีเมล…",
    copyLink: "คัดลอกลิงก์",
    copyLinkHelper: "บันทึกนามบัตรไว้ดูภายหลัง",
    install: "เพิ่มไปยังหน้าจอหลัก",
    installHelper: "iPhone / Android",
    linkCopied: "คัดลอกลิงก์แล้ว คุณสามารถแชร์ได้ทุกที่",
    linkCopiedClipboard: "คัดลอกลิงก์ไปยังคลิปบอร์ดแล้ว",
    copyUnavailable: "ไม่สามารถคัดลอกอัตโนมัติได้ โปรดเลือก URL แล้วคัดลอกด้วยตนเอง",
    alreadyInstalled: "นามบัตรนี้อยู่บนหน้าจอหลักของโทรศัพท์เครื่องนี้แล้ว",
    installRequested: "ส่งคำขอเพิ่มไปยังหน้าจอหลักแล้ว",
    installFailed: "ไม่สามารถเริ่มการเพิ่มไปยังหน้าจอหลักได้",
    iosInstallHelp: "บน iPhone: แตะ แชร์ ใน Safari แล้วเลือก “เพิ่มไปยังหน้าจอโฮม”",
    androidInstallHelp: "บน Android: เปิดเมนูเบราว์เซอร์ แล้วเลือก “เพิ่มไปยังหน้าจอหลัก” หรือ “ติดตั้งแอป”",
    shareTextPrefix: "ค้นพบ",
    call: "โทร",
    mail: "อีเมล",
    saveContact: "บันทึก",
    sendDetails: "ส่งข้อมูลติดต่อของฉัน",
    findUs: "ค้นหาเรา",
    appointment: "นัดหมาย",
    openingHours: "เวลาทำการ",
    interventionZones: "พื้นที่ให้บริการ",
    poweredBy: "ขับเคลื่อนโดย",
    leadIdentityError: "กรอกชื่อ อีเมล หรือหมายเลขโทรศัพท์อย่างน้อยหนึ่งรายการ",
    leadConsentError: "จำเป็นต้องยินยอมก่อนส่งข้อมูลติดต่อ",
    leadGenericError: "ไม่สามารถส่งข้อมูลติดต่อของคุณได้",
    leadDialogTitle: "ส่งข้อมูลติดต่อของฉัน",
    leadSentTitle: "ส่งแล้ว",
    leadSentText: "ผู้ให้บริการได้รับข้อมูลติดต่อของคุณแล้ว",
    leadNameLabel: "ชื่อ-นามสกุล / บริษัท",
    leadNamePlaceholder: "สมชาย ใจดี / บริษัท ตัวอย่าง จำกัด",
    phoneLabel: "โทรศัพท์",
    emailLabel: "อีเมล",
    leadMessageLabel: "ข้อความ / คำขอ",
    leadMessagePlaceholder: "คำขอ ความต้องการ หรือช่วงเวลาที่สะดวก…",
    leadConsent: "ฉันยินยอมให้ส่งข้อมูลติดต่อของฉันแก่ผู้ให้บริการรายนี้",
    leadSubmitting: "กำลังส่ง…",
    leadSubmit: "ส่งข้อมูลติดต่อของฉัน",
    rdvMetaTitle: "นัดหมาย - iNr'Badge",
    rdvTitle: "จองนัดหมาย",
    rdvChooseSlot: "เลือกช่วงเวลา",
    rdvDate: "วันที่",
    rdvTime: "เวลา",
    rdvChooseTime: "เลือกเวลา",
    rdvNoSlot: "ไม่มีช่วงเวลา",
    rdvNoSlotDay: "ไม่มีช่วงเวลาว่างในวันนี้",
    rdvNameLabel: "ชื่อ-นามสกุล *",
    rdvNamePlaceholder: "ชื่อของคุณ",
    rdvCompanyLabel: "บริษัท",
    rdvCompanyPlaceholder: "บริษัทของคุณ",
    rdvMailLabel: "อีเมล *",
    rdvEmailPlaceholder: "your@email.com",
    rdvPhoneLabel: "โทรศัพท์",
    rdvPhonePlaceholder: "หมายเลขโทรศัพท์",
    rdvMessageLabel: "ข้อความ / เหตุผล",
    rdvMessagePlaceholder: "อธิบายความต้องการของคุณโดยย่อ",
    rdvChooseSlotError: "โปรดเลือกช่วงเวลา",
    rdvRequiredError: "ต้องระบุชื่อและอีเมล",
    rdvGenericError: "ไม่สามารถส่งคำขอได้",
    rdvSuccess: "ส่งคำขอแล้ว ผู้ให้บริการจะยืนยันหรือเสนอช่วงเวลาอื่น",
    rdvSubmitting: "กำลังส่ง...",
    rdvSubmit: "ส่งคำขอ",
    rdvNote: "นัดหมายจะถูกเพิ่มใน iNr'Calendar หลังจากผู้ให้บริการยืนยันแล้วเท่านั้น",
    rdvBack: "กลับไปยังนามบัตร",
  },
  zh: {
    close: "关闭",
    shareAria: "分享此名片",
    shareTitle: "分享",
    shareSheetTitle: "联系名片",
    shareSheetDescription: "分享此名片、复制链接或将其添加到主屏幕。",
    shareNative: "分享",
    shareNativeHelper: "WhatsApp、短信、电子邮件…",
    copyLink: "复制链接",
    copyLinkHelper: "保存名片以便稍后查看",
    install: "添加到主屏幕",
    installHelper: "iPhone / Android",
    linkCopied: "链接已复制，现在可以分享到任何地方。",
    linkCopiedClipboard: "链接已复制到剪贴板。",
    copyUnavailable: "无法自动复制。您可以选择 URL 并手动复制。",
    alreadyInstalled: "此名片已在该手机的主屏幕上。",
    installRequested: "已发送添加到主屏幕的请求。",
    installFailed: "无法启动添加到主屏幕的操作。",
    iosInstallHelp: "在 iPhone 上：轻点 Safari 中的“分享”，然后选择“添加到主屏幕”。",
    androidInstallHelp: "在 Android 上：打开浏览器菜单，然后选择“添加到主屏幕”或“安装应用”。",
    shareTextPrefix: "了解",
    call: "致电",
    mail: "电子邮件",
    saveContact: "保存",
    sendDetails: "发送我的联系信息",
    findUs: "找到我们",
    appointment: "预约",
    openingHours: "营业时间",
    interventionZones: "服务区域",
    poweredBy: "技术支持",
    leadIdentityError: "请至少填写姓名、电子邮件或电话号码中的一项。",
    leadConsentError: "发送联系信息前必须同意授权。",
    leadGenericError: "无法发送您的联系信息。",
    leadDialogTitle: "发送我的联系信息",
    leadSentTitle: "已发送。",
    leadSentText: "服务商已收到您的联系信息。",
    leadNameLabel: "姓名 / 公司",
    leadNamePlaceholder: "张伟 / 示例有限公司",
    phoneLabel: "电话",
    emailLabel: "电子邮件",
    leadMessageLabel: "留言 / 请求",
    leadMessagePlaceholder: "您的请求、需求或希望的时间…",
    leadConsent: "我同意将我的联系信息发送给此服务商。",
    leadSubmitting: "正在发送…",
    leadSubmit: "发送我的联系信息",
    rdvMetaTitle: "预约 - iNr'Badge",
    rdvTitle: "预约时间",
    rdvChooseSlot: "选择时段",
    rdvDate: "日期",
    rdvTime: "时间",
    rdvChooseTime: "选择时间",
    rdvNoSlot: "无可用时段",
    rdvNoSlotDay: "当天没有可用时段。",
    rdvNameLabel: "姓名 *",
    rdvNamePlaceholder: "您的姓名",
    rdvCompanyLabel: "公司",
    rdvCompanyPlaceholder: "您的公司",
    rdvMailLabel: "电子邮件 *",
    rdvEmailPlaceholder: "your@email.com",
    rdvPhoneLabel: "电话",
    rdvPhonePlaceholder: "电话号码",
    rdvMessageLabel: "留言 / 原因",
    rdvMessagePlaceholder: "请简要说明您的需求",
    rdvChooseSlotError: "请选择一个时段。",
    rdvRequiredError: "姓名和电子邮件为必填项。",
    rdvGenericError: "无法发送请求。",
    rdvSuccess: "请求已发送。服务商将确认或建议其他时段。",
    rdvSubmitting: "正在发送...",
    rdvSubmit: "发送请求",
    rdvNote: "只有在服务商确认后，预约才会添加到 iNr'Calendar。",
    rdvBack: "返回名片",
  },
};

export function getInrBadgeTexts(language: unknown): InrBadgeTexts {
  return TEXTS[normalizeInrBadgeLanguage(language)];
}
